/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Mon Apr 26 2021 19:18:50 GMT-0500 (CDT).
 */

define(['jointjs', 'css!./styles/PeNDeSWidget.css'], function (joint) {
    'use strict';

    var WIDGET_CLASS = 'pe-n-de-s';

    function PeNDeSWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    PeNDeSWidget.prototype._initialize = function () {
        console.log(joint);
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);
        
        var graph = new joint.dia.Graph();
        var paper = new joint.dia.Paper({
          el: document.getElementById('paper'),
          width: 800,
          height: 350,
          gridSize: 10,
          defaultAnchor: { name: 'perpendicular' },
          defaultConnectionPoint: { name: 'boundary' },
          model: graph
        });

        // Create a dummy header
        this._el.append('<h3>PeNDeS Events:</h3>');

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    PeNDeSWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Adding/Removing/Updating items
    PeNDeSWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
                desc.childrenIds.length + ' ' + label + '.';

            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    PeNDeSWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    PeNDeSWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    PeNDeSWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    PeNDeSWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    PeNDeSWidget.prototype.destroy = function () {
    };

    PeNDeSWidget.prototype.onActivate = function () {
        this._logger.debug('PeNDeSWidget has been activated');
    };

    PeNDeSWidget.prototype.onDeactivate = function () {
        this._logger.debug('PeNDeSWidget has been deactivated');
    };

    return PeNDeSWidget;
});
